// Generated by Wrangler on Fri Apr 12 2024 18:30:52 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  MY_VARIABLE: "test";
  kv_namespaces: [{ binding: "MY_KV"; id: "787537896b1846ffa0757d6434f6f00e" }];
  MY_KV: KVNamespace;
}
